"""
Extract data from African PF/SWF dataset Excel file into data/data.js for the web app.
Run: python extract_data.py
"""
import pandas as pd
import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

EXCEL_FILE = "african_pf and swf_dataset_5.13.26.xlsx"
OUT_DIR = "data"
os.makedirs(OUT_DIR, exist_ok=True)

xl = pd.ExcelFile(EXCEL_FILE)

def safe_val(v):
    if pd.isna(v):
        return None
    if isinstance(v, float) and v == int(v):
        return int(v)
    if hasattr(v, 'item'):
        return v.item()
    if isinstance(v, (int, float, bool, str)):
        return v
    return str(v)

def sheet_to_records(sheet_name, header_row=0):
    df = xl.parse(sheet_name, header=header_row)
    df.columns = [str(c).strip() for c in df.columns]
    df = df.dropna(how='all')
    records = []
    for _, row in df.iterrows():
        rec = {k: safe_val(v) for k, v in row.items()}
        # skip rows that are entirely None
        if any(v is not None for v in rec.values()):
            records.append(rec)
    return records

# Header row map (0-indexed)
HEADER_ROWS = {
    'Sovereign Wealth Funds': 0,
    'Pension Funds': 0,
    'Commitments Database': 0,
    'Pipeline & Mandates': 0,
    'Source Library': 0,
    'Tier 1 Candidates': 2,
    'Funds & LP Co-Investors': 2,
    'DFI Co-Investor Patterns': 2,
    'Country Summary': 2,
    'Regulatory vs Behaviour': 2,
    'Absentees Investigation': 2,
    'Inclusion Audit': 0,
    'Omission Candidates': 0,
}

data = {}
for sheet, hrow in HEADER_ROWS.items():
    records = sheet_to_records(sheet, hrow)
    # clean up: drop rows that look like sub-headers (where first value matches column name)
    col0 = list(records[0].keys())[0] if records else None
    if col0:
        records = [r for r in records if r.get(col0) != col0]
    data[sheet] = records
    print(f"{sheet}: {len(records)} rows")

# Write as JS module
js_lines = ["// Auto-generated by extract_data.py — do not edit manually\n"]
js_lines.append("const DATASET = {\n")
for sheet, records in data.items():
    key = sheet.replace(' ', '_').replace('&', 'and').replace('/', '_')
    js_lines.append(f"  {json.dumps(key)}: {json.dumps(records, ensure_ascii=False, indent=2)},\n")
js_lines.append("};\n")

out_path = os.path.join(OUT_DIR, "data.js")
with open(out_path, 'w', encoding='utf-8') as f:
    f.writelines(js_lines)

print(f"\nWrote {out_path}")
print(f"File size: {os.path.getsize(out_path):,} bytes")
